const knex = require("knex");

exports.seed = (knex) => {
  knex("items").insert([
    { name: "Slim", type: "Pasta" },
    { name: "Average", type: "Pasta" },
    { name: "Thick", type: "Pasta" },
    { name: "Small", type: "Size" },
    { name: "Medium", type: "Size" },
    { name: "Big", type: "Size" },
    { name: "Family", type: "Size" },
    { name: "Traditional Tomato", type: "Sauce" },
    { name: "Gorgonzola Sauce", type: "Sauce" },
    { name: "Parisian Sauce", type: "Sauce" },
    { name: "Mozzarella", type: "Topping" },
    { name: "Parmesan", type: "Topping" },
    { name: "Provolone", type: "Topping" },
    { name: "Catupiry", type: "Topping" },
    { name: "Tomato", type: "Topping" },
    { name: "Oregano", type: "Topping" },
    { name: "Olives", type: "Topping" },
    { name: "Onion", type: "Topping" },
    { name: "Ham", type: "Topping" },
    { name: "Pepperoni", type: "Topping" },
    { name: "Sausage", type: "Topping" },
    { name: "Black Olives", type: "Topping" },
    { name: "Garlic", type: "Topping" },
    { name: "Olive oil", type: "Topping" },
    { name: "Anchovies", type: "Topping" },
    { name: "Margherita", type: "Premade" },
    { name: "Mozzarella", type: "Premade" },
    { name: "Pepperoni", type: "Premade" },
    { name: "Four Cheeses", type: "Premade" },
    { name: "Pomodoro", type: "Premade" },
    { name: "Marinara", type: "Premade" },
    { name: "Calzone", type: "Premade" },
    { name: "Vegetarian", type: "Premade" },
  ]);
};
